spring:
  sendgrid:
    api-key: SG.7kYqpyobR5GWd75-ooXWrQ.yQg7jJ7YN5-xgIkBYicSEhobErpYdmYdJQkzEDitp3Q
  #    password: itArPrishtineagon
  datasource:
    url: "ec2-54-220-14-54.eu-west-1.compute.amazonaws.com/d3mruoemrltoeg"
    username: "liubxnbibgnawf"
    password: "7a40ecf3e349ca393f3b06205c12999675a68ac22095f62f43874fccd4efc918"
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  flyway:
    baselineOnMigrate: true
    enabled: false
    url: "ec2-54-220-14-54.eu-west-1.compute.amazonaws.com"
    user: "liubxnbibgnawf"
    password: "7a40ecf3e349ca393f3b06205c12999675a68ac22095f62f43874fccd4efc918"

