spring:
  sendgrid:
    api-key: SG.7kYqpyobR5GWd75-ooXWrQ.yQg7jJ7YN5-xgIkBYicSEhobErpYdmYdJQkzEDitp3Q
  datasource:
    url: "jdbc:postgresql://ec2-54-158-247-210.compute-1.amazonaws.com/daa54gokh4p01m"
    username: "zukhhgcdiznaca"
    password: "83b009625a5ec34ee4b265a46cb697d95b1c5917d73c8a164672e5e517ed931e"
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  flyway:
    baselineOnMigrate: true
    enabled: false
    url: "jdbc:postgresql://ec2-54-220-14-54.eu-west-1.compute.amazonaws.com/d3mruoemrltoeg"
    user: "liubxnbibgnawf"
    password: "7a40ecf3e349ca393f3b06205c12999675a68ac22095f62f43874fccd4efc918"

links:
  webapp_base: "https://modest-heisenberg-5b9526.netlify.app/"
  book_details: "https://modest-heisenberg-5b9526.netlify.app/account/biblioteka/book-details/"

jwt:
  secret: arPrishtineDev2021
  expiration: 24
